services:
  client:
    image: crm-dev-i
    build:
      dockerfile: Dockerfile.dev
    container_name: crm-dev-i
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    
volumes:
  node_modules: